package httpapi

import ("encoding/json"; "fmt"; "net/http"; "wip/internal/app")

// handleComponentAction starts, stops, or opens a component terminal session.
func (s *Server) handleComponentAction(w http.ResponseWriter, r *http.Request, id, action string) {
	var body struct { Component string `json:"component"`; Input string `json:"input"` }; if err := json.NewDecoder(r.Body).Decode(&body); err != nil { http.Error(w, "invalid request body", http.StatusBadRequest); return }; if body.Component == "" { http.Error(w, "component is required", http.StatusBadRequest); return }
	entry, err := s.store.GetApp(id); if err != nil { http.Error(w, err.Error(), http.StatusNotFound); return }; var component app.Component; found := false; for _, candidate := range entry.Components { if candidate.Name == body.Component { component, found = candidate, true; break } }; if !found { http.Error(w, fmt.Sprintf("component %q not found", body.Component), http.StatusNotFound); return }
	if action == "terminal" { if body.Input != "" { if err := s.processManager.SendTerminalInput(id, body.Component, body.Input); err != nil { http.Error(w, err.Error(), http.StatusInternalServerError); return }; writeJSON(w, map[string]string{"status": "ok"}); return }; if err := s.processManager.OpenTerminal(id, body.Component); err != nil { http.Error(w, err.Error(), http.StatusInternalServerError); return }; writeJSON(w, map[string]string{"status": "ok", "component": body.Component}); return }
	response := map[string]interface{}{"status": "ok", "url": "", "logs": []string{}}
	if action == "start" { if err := s.processManager.Start(id, entry.LocalPath, component); err != nil { s.recordActivity(entry, "component.start", fmt.Sprintf("Started %s", component.Name), entry.DefaultBranch, "", "stopped", "Component failed to start", "failure", err.Error()); http.Error(w, err.Error(), http.StatusInternalServerError); return }; s.runtime.SetRunning(id, body.Component, true); response["url"] = app.InferBrowseURL(component); response["logs"] = s.processManager.GetComponentLogs(id, body.Component); s.recordActivity(entry, "component.start", fmt.Sprintf("Started %s", component.Name), entry.DefaultBranch, "", "running", "Component process started", "success", "") } else { if err := s.processManager.Stop(id, entry.LocalPath, component); err != nil { s.recordActivity(entry, "component.stop", fmt.Sprintf("Stopped %s", component.Name), entry.DefaultBranch, "", "running", "Component failed to stop", "failure", err.Error()); http.Error(w, err.Error(), http.StatusInternalServerError); return }; s.runtime.SetRunning(id, body.Component, false); response["logs"] = s.processManager.GetComponentLogs(id, body.Component); s.recordActivity(entry, "component.stop", fmt.Sprintf("Stopped %s", component.Name), entry.DefaultBranch, "", "stopped", "Component process stopped", "success", "") }; writeJSON(w, response)
}

// handleUpdateComponents validates and replaces an app's component definitions.
func (s *Server) handleUpdateComponents(w http.ResponseWriter, r *http.Request, id string) {
	if r.Method != http.MethodPut { http.Error(w, "method not allowed", http.StatusMethodNotAllowed); return }; var body struct { Components []app.Component `json:"components"` }; if err := json.NewDecoder(r.Body).Decode(&body); err != nil { http.Error(w, "invalid request body", http.StatusBadRequest); return }
	for i, component := range body.Components { if component.Name == "" { http.Error(w, fmt.Sprintf("component %d: name is required", i), http.StatusBadRequest); return }; switch component.RunMode { case app.RunModeDocker, app.RunModeNative: case "": body.Components[i].RunMode = app.RunModeNative; default: http.Error(w, fmt.Sprintf("component %d: invalid run mode %q", i, component.RunMode), http.StatusBadRequest); return } }
	if err := s.store.UpdateComponents(id, body.Components); err != nil { http.Error(w, err.Error(), http.StatusInternalServerError); return }; entry, err := s.store.GetApp(id); if err != nil { http.Error(w, err.Error(), http.StatusInternalServerError); return }; s.recordActivity(entry, "components.updated", "Updated app components", entry.DefaultBranch, "", "stopped", "Saved component start and stop configuration", "success", ""); writeJSON(w, s.withConnections(entry))
}